language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - PHPUNIT_VERSION="3.7.*"
  - PHPUNIT_VERSION="3.8.*"
  - PHPUNIT_VERSION="4.0.*"
  
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer require phpunit/phpunit=$PHPUNIT_VERSION
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit-unit.xml.dist
  - vendor/bin/phpunit --configuration phpunit-integration.xml.dist
  - vendor/bin/athletic --path tests/PHPUnit/Tests/Runner/CleverAndSmart/Benchmark --bootstrap tests/PHPUnit/Tests/Runner/CleverAndSmart/Benchmark/bootstrap.php --formatter GroupedFormatter
